### ISSUE TITLE
installation fails on 3.5 or if already installed from previous versions of blender, it seems to interfere with the new category based menu

### ISSUE THREAD

**Issue by nrfm** [carson-katri/geometry-script#16]
I just upgraded to 3.5 and the new categories' based menu  was not showing the node list for any category, only the categories.

When I disabled the addon the menu started working.

Alos, this error is thrown when I try to re-enable the addon.

```Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/osmn/Library/Application Support/Blender/3.5/scripts/addons/geometry-script-main/__init__.py", line 22, in <module>
    from .api.tree import *
  File "/Users/osmn/Library/Application Support/Blender/3.5/scripts/addons/geometry-script-main/api/tree.py", line 9, in <module>
    from .node_mapper import *
  File "/Users/osmn/Library/Application Support/Blender/3.5/scripts/addons/geometry-script-main/api/node_mapper.py", line 124, in <module>
    category.draw(CategoryStub(), None)
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/startup/bl_ui/node_add_menu_geometry.py", line 505, in draw
    layout.menu("NODE_MT_geometry_node_GEO_COLOR")
AttributeError: 'Layout' object has no attribute 'menu'```

Many thanks for your great work ( opening an issue without saying thanks feels bad..  )

**Comment by carson-katri** [comment]
Thanks for pointing this out! I've just updated the add-on to support the 3.5 release.
