### ISSUE TITLE
Cant get geometry script to work on blender 3.5

### ISSUE THREAD

**Issue by MrPositivity** [carson-katri/geometry-script#20]
Im trying out Geometry Script, but I cant get it to work. 
when I run script for Repeat Grid.py its not makeing node tree correctly like in image in the documentation, not sure what is wrong
It looks like this -  https://i.imgur.com/7jXvyIH.png

am I missing something ? 
it also gives this error when I press Run Script 
 ```
Python: Traceback (most recent call last):
  File "C:\Users\Positivity\Desktop\GN_Test01.blend\Repeat Grid.py", line 4, in <module>
  File "C:\Users\Positivity\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\geometry-script-main\api\tree.py", line 98, in build_tree
    outputs = builder(**builder_inputs)
  File "C:\Users\Positivity\Desktop\GN_Test01.blend\Repeat Grid.py", line 8, in repeat_grid
TypeError: 'NoneType' object is not callable
```

**Comment by carson-katri** [comment]
Some nodes changed in Blender 3.5, you may need to add `.mesh` after the call to `grid(…)`:

```python
from geometry_script import *

@tree("Repeat Grid")
def repeat_grid(geometry: Geometry, width: Int, height: Int):
    g = grid(
        size_x=width, size_y=height,
        vertices_x=width, vertices_y=height
    ).mesh.mesh_to_points()
    return g.instance_on_points(instance=geometry)
```

**Comment by TheOtherRealm** [comment]
I can confirm that it is an issue with 3.5 - works great in 3.4.1

**Comment by HUisHU-Christian** [comment]
It doesn't seem to be working in Blender 3.6 as well. Is there a fix for this already or are there any plans for fixes soon or do we need to patch this on ourself?

**Comment by HUisHU-Christian** [comment]
To answer my own question: The main branch does have the fixes applied and it seems to be working. It's just that a recent release seems to be missing. Maybe it's time for a new release now that blender 3.6 is out?

**Comment by HUisHU-Christian** [comment]
Well it installs, but the example script refused to run (for the same reasons):
TypeError: 'NoneType' object is not callable
