### ISSUE TITLE
Training Google Bard to write Geometry Script, case of Volume Cube instancing Icosphere

### ISSUE THREAD

**Issue by enzyme69** [carson-katri/geometry-script#27]
I have this working alright, but...

![Screenshot 2023-07-20 at 11 04 11 am](https://github.com/carson-katri/geometry-script/assets/3952687/19964d19-1aa0-40b5-843d-71b7c85efe49)

```python
from geometry_script import *

@tree("Repeat Cube")
def repeat_cube(geometry: Geometry, size: Float, seed: Int, density: Float):
    """Creates a cube of points and instances them."""
    points = volume_cube(size=size).distribute_points_in_volume(
        seed=seed, density=density
    )
    return points.instance_on_points(instance=geometry)

```

**Comment by enzyme69** [comment]
Below, modified version, which supposed to instance icosphere, failed:

```python
from geometry_script import *

@tree("Repeat Cube")
def repeat_cube(geometry: Geometry, size: Float, seed: Int, density: Float):
    """Creates a cube of points and instances them."""
    points = volume_cube(size=size).distribute_points_in_volume(
        seed=seed, density=density
    )
    instanced_points = points.instance_on_points(instance=ico_sphere(radius=0.5)).realize_instances()
    return instanced_points.mesh_to_volume().volume_to_mesh()

```

**Comment by enzyme69** [comment]
Error message: -- this happens quite often, any idea why?

```
Python: Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/geometry-script-main/api/node_mapper.py", line 54, in set_or_create_link
    node_input.default_value = x
AttributeError: 'NodeSocketGeometry' object has no attribute 'default_value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jimmygunawan/Desktop/volume_cube_density_seed1.blend/Text", line 4, in <module>
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/geometry-script-main/api/tree.py", line 98, in build_tree
    outputs = builder(**builder_inputs)
  File "/Users/jimmygunawan/Desktop/volume_cube_density_seed1.blend/Text", line 9, in repeat_cube
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/geometry-script-main/api/node_mapper.py", line 94, in build
    return build_node(node_type)(self, *args, **kwargs)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/geometry-script-main/api/node_mapper.py", line 69, in build
    set_or_create_link(value, node_input)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/geometry-script-main/api/node_mapper.py", line 56, in set_or_create_link
    link_constant()
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/geometry-script-main/api/node_mapper.py", line 48, in link_constant
    constant = Type(value=x)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/geometry-script-main/api/types.py", line 48, in __init__
    raise Exception(f"'{value}' cannot be expressed as a node.")
Exception: '{'mesh': <geometry-script-main.api.types.Type object at 0x2ba2f70d0>, 'uv_map': <geometry-script-main.api.types.Type object at 0x2ba2f70a0>}' cannot be expressed as a node.

```

**Comment by enzyme69** [comment]
Ok I figured it out:

```
from geometry_script import *

@tree("Repeat Cube")
def repeat_cube(geometry: Geometry, size: Float, seed: Int, density: Float):
    """Creates a cube of points and instances them."""
    points = volume_cube(size=size).distribute_points_in_volume(
        seed=seed, density=density
    )
    instanced_points = points.instance_on_points(instance=ico_sphere(radius=0.5).mesh).realize_instances()
    return instanced_points.mesh_to_volume().volume_to_mesh()

```
