### ISSUE TITLE
Does not work for me on Blender 3.6

### ISSUE THREAD

**Issue by rsaccon** [carson-katri/geometry-script#32]
I just installed the addon from your latest zip, copy pasted the `Repeat Grid` example into the Blender Text Editor and tried to run it. Unfortunately I got an error:
```
Error: Python: Traceback (most recent call last):
  File "/Repeat Grid.py", line 5, in <module>
  File "/Users/robertosaccon/Library/Application Support/Blender/3.6/scripts/addons/geometry-script-main/api/tree.py", line 41, in build_tree
    node_group.is_modifier = True
AttributeError: 'GeometryNodeTree' object has no attribute 'is_modifier'
```

did I do anything wrong ?

**Comment by alphadito** [comment]
The [latest](https://github.com/carson-katri/geometry-script/pull/30) merge has breaking changes due to moving from Blender 3.6 -> 4.0. For Blender 3.6 you can download the [previous](https://github.com/carson-katri/geometry-script/tree/63a75169059f683a31d340fd96a80c17f9645a5e) version.

**Comment by carson-katri** [comment]
We should probably add version checks for 4.0 specific changes

**Comment by rsaccon** [comment]
Thanks a lot, the previous version works perfectly. Now I am gonna deep dive into it. Yeah, version checks would be great, I anticipate more people like have to stick to Blender 3.6 for now (I have a 2013 Macbook Pro, where Blender >=  4.0 does not run anymore).

**Comment by alphadito** [comment]
@carson-katri  Hmm... how about something like this in `tree.py`? 

```python
def check_version(min_major, min_minor, min_patch):
    major, minor, patch = bpy.app.version
    if (major, minor, patch) < (min_major, min_minor, min_patch):
        raise Exception(f"Your Blender version {major}.{minor}.{patch} is not compatible. "
                        f"Geometry Script now requires at least Blender {min_major}.{min_minor}.{min_patch}. "
                        f"Please update Blender or install a previous version of Geometry Script.")

def tree(name):
    check_version(4, 0, 0)
    ...
    def build_tree(builder):
        ...
```

**Comment by carson-katri** [comment]
@alphadito I meant backwards compatibility, so we could switch back to the 3.x method as needed.

Could optionally create custom abstractions that expose a unified API for all versions.

**Comment by alphadito** [comment]
Ah yep I initially tried to do a bit of monkey patching for backwards compatibility but the bpy.types.GeometryNodeTree class appears to have a read only __ slots __ attribute defined so you can't just mutate the blender 3.6 object to have 4.0 attribute names.

Perhaps we could make a wrapper class?
```python
class NodeGroupWrapper:
    def __init__(self,nodegroup,version):
        self.nodegroup = nodegroup
        self.version = version 
    @property
    def inputs(self):
        if self.version[0] < 4:
            return self.nodegroup.inputs
        else:
            return [i for i in self.nodegroup.interface.items_tree if i.item_type == 'SOCKET' and i.in_out == 'INPUT'] 
```

**Comment by MadMaia3D** [comment]
Unfortunately for me it's not working either.
I just install the addon, paste the example script in blender and it generates the same error both on 3.6 and 4.0

Blender 3.6:

Python: Traceback (most recent call last):
  File "C:\Users\guilherme\Desktop\temp.blend\Text", line 4, in <module>
  File "C:\Users\guilherme\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\geometry-script-main\api\tree.py", line 136, in build_tree
    outputs = builder(**builder_inputs)
  File "C:\Users\guilherme\Desktop\temp.blend\Text", line 8, in repeat_grid
TypeError: 'NoneType' object is not callable


Blender 4.0:

Python: Traceback (most recent call last):
  File "C:\Users\guilherme\Desktop\temp.blend\Text", line 4, in <module>
  File "C:\Users\guilherme\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\geometry-script-main\api\tree.py", line 136, in build_tree
    outputs = builder(**builder_inputs)
  File "C:\Users\guilherme\Desktop\temp.blend\Text", line 8, in repeat_grid
TypeError: 'NoneType' object is not callable
