### ISSUE TITLE
Blender 3.6 error installing

### ISSUE THREAD

**Issue by enzyme69** [carson-katri/geometry-script#45]
I have latest Blender 3.6 but has issue installing the addon. 

```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/geometry_script/__init__.py", line 22, in <module>
    from .api.tree import *
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/geometry_script/api/tree.py", line 9, in <module>
    from .node_mapper import *
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/geometry_script/api/node_mapper.py", line 124, in <module>
    category.draw(CategoryStub(), None)
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/startup/bl_ui/node_add_menu_geometry.py", line 459, in draw
    if context.preferences.experimental.use_new_volume_nodes:
AttributeError: 'NoneType' object has no attribute 'preferences'

```

**Comment by alphadito** [comment]
Try with the latest commit of the main branch.
