### ISSUE TITLE
official testing code failed ...

### ISSUE THREAD

**Issue by pterusgithub** [carson-katri/geometry-script#56]
Hello,
Wanting to try geometry-script, I started following the documentation. No problems during installation. No worries either for the first demo code. 
On the other hand, here is the error message that I get with the following script...
script
```python
from geometry_script import *

@tree("Cube Tree")
def cube_tree():
    return cube(), 5
```
output
```shell
Python: Traceback (most recent call last):
  File "/test.py", line 3, in <module>
  File "/pathto/.config/blender/4.2/scripts/addons/geometry-script-main/api/tree.py", line 152, in build_tree
    result = Type(value=result)
             ^^^^^^^^^^^^^^^^^^
  File "/pathto/.config/blender/4.2/scripts/addons/geometry-script-main/api/types.py", line 57, in __init__
    raise Exception(f"'{value}' cannot be expressed as a node.")
Exception: '{'mesh': <geometry-script-main.api.types.Type object at 0x7e00479e7550>, 'uv_map': <geometry-script-main.api.types.Type object at 0x7e00479ee090>}' cannot be expressed as a node.
```
Could you direct me to the origin of the problem?
I'm taking this opportunity to find out if you plan to maintain the project in the long term (since blender evolves very quickly...), thank you for your feedback

**Comment by pterusgithub** [comment]
resolved ! 

```python
from geometry_script import *

@tree("Cube Tree")
def cube_tree():
    return cube(), 5
```

PS: my second question remains ;-) = Do you plan to maintain the project in the long term (since blender evolves very quickly...)? 
thank you for your feedback

**Comment by carson-katri** [comment]
Yeah, it should be fairly low-maintenance since it generates all of the functions from the nodes available in the Blender installation.

**Comment by pterusgithub** [comment]
thanks for the feedback,

Do you know if there are other sources to learn how to use it? (discussion forums, sites where you can find script examples???)
I found a few sources including a youtube video but not much more...
Thanks !

**Comment by carson-katri** [comment]
There are guides here: https://carson-katri.github.io/geometry-script/
