### ISSUE TITLE
capture trouble

### ISSUE THREAD

**Issue by pterusgithub** [carson-katri/geometry-script#58]
Hello,
 
I've some problem with the capture attribute node in blender 4.2

here the error:
```shell
Python: Traceback (most recent call last):
  File "file.py", line 182, in <module>
  File "/pathto/.config/blender/4.2/scripts/addons/geometry-script-main/api/tree.py", line 136, in build_tree
    outputs = builder(**builder_inputs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "file.py", line 186, in attributs
AttributeError: type object 'CaptureAttribute' has no attribute 'DataType'
```

with the line code:
```python
capture_attribute(data_type=CaptureAttribute.DataType.FLOAT_VECTOR, domain=CaptureAttribute.Domain.POINT, geometry=c,value=position())
```
Would it be possible to have an updated example of use of this node?

Thank you

**Comment by pterusgithub** [comment]
I would like to use the capture attribute node in this context. Anyone for a little helping hand?

THANKS
![image](https://github.com/user-attachments/assets/dfbf4af4-6a30-499c-ae09-e2b85cdae875)
